POST http://localhost:3001/api/family-plan-request/send-request
Content-Type: application/json

{
    "recepientId": "60fb00b7597621002b5ba866",
    "requester": "60fafe50597621002b5ba859",
    "planName": "And another one :))))",
    "planId": "60ff9d81bf7e4300e4ec5f94"
}