version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    networks:
      - budget-app
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    networks:
      - budget-app
networks:
  budget-app:
    driver: bridge
