version: '3'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    networks:
      - budget-app
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    ports:
      - 3001:3001
    environment:
      ELASTICSEARCH_HOST: 'elasticsearch:9200'
    networks:
      - budget-app
    depends_on:
      - redis
      - elasticsearch
    command: ['npm', 'test']
  redis:
    image: redis:6-alpine
    container_name: redis
    networks:
      - budget-app
    ports:
      - 6379:6379
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - discovery.type=single-node
    logging:
      driver: none
    ports:
      - 9300:9300
      - 9200:9200
    networks:
      - budget-app
networks:
  budget-app:
    driver: bridge
volumes:
  esdata:
